GET   http://localhost:4017/api/garments
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7InVzZXJuYW1lIjoic2ltZWxhbmUtanBkIn0sImlhdCI6MTY1MTIzMjI0MX0.jIWGE1YjC6qs5dAzZWQrUxdxyZ2HdDpE_udkWAIK2ko



###
POST http://localhost:4017/auth 
Content-Type: application/json


{
  "username": "simelane-jpd"
  
}



###
GET http://localhost:4017/api/garments/price/:price


