GET   http://localhost:4017/api/garments
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNpbWVsYW5lLWpwZCJ9.PqdZgojd_s_W938MoI1x9_pemDeLmhHy7R1QgRIjEH0





###
POST http://localhost:4017/auth 
Content-Type: application/json


{
  "username": "simelane-jpd"
  
}



###
GET http://localhost:4017/api/garments/price/:price


